language: c

script: "./travis-tool.sh run_tests"

before_script:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- sudo apt-get install -y libv8-dev
- "./travis-tool.sh bootstrap"
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_bioc sangerseqR"
- "./travis-tool.sh github_package jimhester/robustr jimhester/covr sckott/ridigbio@search-fix ropensci/rebird"

after_success:
- Rscript -e 'library(covr); coveralls()'

notifications:
  slack:
    secure: JgCatgv7Eeh6qHmi3TwWLdKHkCjnr5KHcBzVwy2F4IPafqPMEEhnSFxqP2Td8f7YcPqvdiv/blTGdgIOAi3V64O4fp3NZLLpzINNiL0i9iBZqkT71uw8ovcfrAeIHA9D9gapLtx3D4hdUF9jIyLIW2kMzIvaIA5PiDJ+oZitHow=
